"""Reference list of the equations used in calculator.py, with the meaning of each term.

Each entry follows the calculation in calculator.calculate(). Angles are in
degrees in the formulas unless the term says otherwise; trigonometric
functions in the code take radians, which the formulas here leave implicit.
"""

# Each equation: ref, title, formula (plain text), terms [(symbol, meaning, unit)].
# Each section groups related equations under a heading.
EQUATION_SECTIONS = [
    ("Basic proportions (clause 4)", [
        {"ref": "Eq. (1)", "title": "Gear ratio",
         "formula": "u = z2 / z1",
         "terms": [("u", "gear ratio", "-"),
                   ("z2", "number of teeth in the worm wheel", "-"),
                   ("z1", "number of starts (threads) of the worm", "-")]},
        {"ref": "Eq. (2)", "title": "Worm pitch diameter, first approximation",
         "formula": "dw1' = a^0.875 / 1.47",
         "terms": [("dw1'", "first-approximation worm pitch diameter", "mm"),
                   ("a", "center distance", "mm")]},
        {"ref": "Eq. (2) → m_a,rec", "title": "Axial module implied by Eq. (2)",
         "formula": "m_a,rec = (2a - dw1') / z2",
         "terms": [("m_a,rec", "axial module that gives the Eq. (2) worm diameter", "mm"),
                   ("a", "center distance", "mm"),
                   ("dw1'", "first-approximation worm pitch diameter", "mm"),
                   ("z2", "number of teeth in the worm wheel", "-")]},
        {"ref": "Eq. (3)", "title": "Minimum worm root diameter",
         "formula": "df1,min = a^0.875 / 2",
         "terms": [("df1,min", "minimum worm root diameter", "mm"),
                   ("a", "center distance", "mm")]},
        {"ref": "Eq. (4)", "title": "Worm pitch diameter",
         "formula": "dw1 = 2a - dw2",
         "terms": [("dw1", "worm pitch diameter", "mm"),
                   ("a", "center distance", "mm"),
                   ("dw2", "gear pitch diameter", "mm")]},
        {"ref": "Eq. (5)", "title": "Circular pitch (gear, transverse plane)",
         "formula": "pt2 = π · dw2 / z2",
         "terms": [("pt2", "transverse circular pitch; equals the worm axial pitch", "mm"),
                   ("dw2", "gear pitch diameter", "mm"),
                   ("z2", "number of teeth in the worm wheel", "-")]},
        {"ref": "Eq. (6)", "title": "Gear pitch diameter",
         "formula": "dw2 = m_a · z2",
         "terms": [("dw2", "gear pitch diameter", "mm"),
                   ("m_a", "axial module", "mm"),
                   ("z2", "number of teeth in the worm wheel", "-")]},
        {"ref": "Eq. (7)", "title": "Lead angle at the pitch point",
         "formula": "δm1 = atan( dw2 / (dw1 · u) )",
         "terms": [("δm1", "lead angle at the pitch point", "deg"),
                   ("dw2", "gear pitch diameter", "mm"),
                   ("dw1", "worm pitch diameter", "mm"),
                   ("u", "gear ratio", "-")]},
        {"ref": "Eq. (8)", "title": "Normal circular pitch",
         "formula": "pn1 = pt2 · cos δm1",
         "terms": [("pn1", "normal circular pitch", "mm"),
                   ("pt2", "transverse circular pitch", "mm"),
                   ("δm1", "lead angle at the pitch point", "deg")]},
        {"ref": "Eq. (9)", "title": "Normal module",
         "formula": "mn = m_a · cos δm1",
         "terms": [("mn", "normal module", "mm"),
                   ("m_a", "axial module", "mm"),
                   ("δm1", "lead angle at the pitch point", "deg")]},
        {"ref": "Eq. (10)", "title": "Whole depth (worm and gear)",
         "formula": "h1 = h2 = pn1 / 2",
         "terms": [("h1, h2", "whole depth of worm thread and gear tooth", "mm"),
                   ("pn1", "normal circular pitch", "mm")]},
        {"ref": "Eq. (11)", "title": "Working depth",
         "formula": "hw = 0.9 · h",
         "terms": [("hw", "working depth", "mm"),
                   ("h", "whole depth (h1 = h2)", "mm")]},
        {"ref": "Eq. (12)", "title": "Addendum",
         "formula": "ham = hw / 2",
         "terms": [("ham1 = ham2", "addendum of worm and gear", "mm"),
                   ("hw", "working depth", "mm")]},
        {"ref": "Eqs. (13), (14)", "title": "Clearance",
         "formula": "c = h - hw",
         "terms": [("c1 = c2", "clearance of worm and gear", "mm"),
                   ("h", "whole depth", "mm"),
                   ("hw", "working depth", "mm")]},
        {"ref": "Eqs. (15), (16)", "title": "Dedendum",
         "formula": "hfm = h - ham",
         "terms": [("hfm1 = hfm2", "dedendum of worm and gear", "mm"),
                   ("h", "whole depth", "mm"),
                   ("ham", "addendum", "mm")]},
        {"ref": "Eq. (17)", "title": "Worm throat diameter",
         "formula": "da1 = dw1 + 2 · ham",
         "terms": [("da1", "worm throat (outside) diameter", "mm"),
                   ("dw1", "worm pitch diameter", "mm"),
                   ("ham", "addendum", "mm")]},
        {"ref": "Eq. (18)", "title": "Worm root diameter",
         "formula": "df1 = dw1 - 2 · hfm",
         "terms": [("df1", "worm root diameter", "mm"),
                   ("dw1", "worm pitch diameter", "mm"),
                   ("hfm", "dedendum", "mm")]},
        {"ref": "Eq. (19)", "title": "Axial pressure angle",
         "formula": "αx = atan( tan αn / cos δm1 )",
         "terms": [("αx", "axial pressure angle", "deg"),
                   ("αn", "normal pressure angle", "deg"),
                   ("δm1", "lead angle at the pitch point", "deg")]},
        {"ref": "Eq. (20)", "title": "Base diameter (Hindley design)",
         "formula": "db = dw2 · sin( αx + 180° · sx2 / (pt2 · z2) )",
         "terms": [("db", "base diameter", "mm"),
                   ("dw2", "gear pitch diameter", "mm"),
                   ("αx", "axial pressure angle", "deg"),
                   ("sx2", "axial gear tooth thickness", "mm"),
                   ("pt2", "transverse circular pitch", "mm"),
                   ("z2", "number of teeth in the worm wheel", "-")]},
        {"ref": "Eq. (21)", "title": "Effective worm thread length",
         "formula": "b1eff = db - 0.02 · a",
         "terms": [("b1eff", "effective worm thread length", "mm"),
                   ("db", "base diameter", "mm"),
                   ("a", "center distance", "mm")]},
        {"ref": "Eqs. (22), (23)", "title": "Worm flat length on the outside diameter",
         "formula": "bf1 = pt2 / 5.5",
         "terms": [("bf1", "worm flat length on the outside diameter", "mm"),
                   ("pt2", "transverse circular pitch", "mm")]},
        {"ref": "Eq. (24)", "title": "Gear root form radius",
         "formula": "rf2 = 2c + 0.5 · da1",
         "terms": [("rf2", "gear root form radius", "mm"),
                   ("c", "clearance", "mm"),
                   ("da1", "worm throat diameter", "mm")]},
        {"ref": "Eq. (25)", "title": "Worm throat form radius (approx.)",
         "formula": "rg1 = 1.06 · (a - da1 / 2)",
         "terms": [("rg1", "worm throat form radius", "mm"),
                   ("a", "center distance", "mm"),
                   ("da1", "worm throat diameter", "mm")]},
        {"ref": "Eq. (26)", "title": "Gear throat form radius",
         "formula": "rg2 = rf2 - h",
         "terms": [("rg2", "gear throat form radius", "mm"),
                   ("rf2", "gear root form radius", "mm"),
                   ("h", "whole depth", "mm")]},
        {"ref": "Clause 4.20", "title": "Tooth and thread thickness (axial)",
         "formula": "sx2 = 0.55 · pt2 ;  sx1 = 0.45 · pt2 - jx",
         "terms": [("sx2", "axial gear tooth thickness", "mm"),
                   ("sx1", "axial worm thread thickness", "mm"),
                   ("pt2", "transverse circular pitch", "mm"),
                   ("jx", "backlash on the gear pitch circle", "mm")]},
        {"ref": "Clause 2.2", "title": "Gear throat and root diameters (central plane)",
         "formula": "da2 = dw2 + 2 · ham ;  df2 = dw2 - 2 · hfm",
         "terms": [("da2", "gear throat diameter", "mm"),
                   ("df2", "gear root diameter", "mm"),
                   ("dw2", "gear pitch diameter", "mm"),
                   ("ham, hfm", "addendum and dedendum", "mm")]},
        {"ref": "Clause 4.26", "title": "Gear face width",
         "formula": "b2 = df1",
         "terms": [("b2", "gear face width", "mm"),
                   ("df1", "worm root diameter", "mm")]},
    ]),
    ("Rating (clause 8, Annexes D, F, G)", [
        {"ref": "Eq. (27)", "title": "Input power rating",
         "formula": "P1 = 0.746 · n1 / u · Zw · Zu · Zm · Zv",
         "terms": [("P1", "input power rating at service factor 1.0", "kW"),
                   ("n1", "worm speed", "rpm"),
                   ("u", "gear ratio", "-"),
                   ("Zw", "basic pressure factor", "-"),
                   ("Zu", "ratio correction factor", "-"),
                   ("Zm", "face width and materials factor", "-"),
                   ("Zv", "velocity factor", "-")]},
        {"ref": "Eq. (28)", "title": "Sliding velocity",
         "formula": "Vg = n1 · da1 / (19 098 · cos δm1)",
         "terms": [("Vg", "sliding velocity", "m/s"),
                   ("n1", "worm speed", "rpm"),
                   ("da1", "worm throat diameter", "mm"),
                   ("δm1", "lead angle at the pitch point", "deg")]},
        {"ref": "Annex G.2", "title": "Basic pressure factor Zw (piecewise, a in mm, x = a/25.4)",
         "formula": ("a ≤ 76:        Zw = e^-4.338672 · x^2.7067619\n"
                     "76 < a ≤ 102:  Zw = 1.714961 - 111.19805 / a\n"
                     "102 < a < 152: Zw = 0.0205315 · a - 1.463167\n"
                     "152 ≤ a ≤ 305: Zw = e^-4.347204 · x^2.7106719\n"
                     "305 < a < 554: Zw = e^-4.380836 · x^2.72856\n"
                     "554 ≤ a ≤ 864: Zw = e^-4.36964 · x^2.72078\n"
                     "a > 864:       Zw = e^-4.571009 · x^2.773764"),
         "terms": [("Zw", "basic pressure factor", "-"),
                   ("a", "center distance", "mm"),
                   ("x", "center distance in inches (a/25.4)", "-")]},
        {"ref": "Annex G.3", "title": "Ratio correction factor Zu (piecewise, in u)",
         "formula": ("u < 4:      Zu = 0.067691 + 0.105 · u\n"
                     "4 ≤ u ≤ 6:  Zu = e^-1.431246 · u^0.51719644\n"
                     "6 < u ≤ 8:  Zu = 1 / (2.111389 - 0.075855 · u)\n"
                     "8 < u ≤ 11: Zu = e^-0.5540175 · e^(0.0180814 · u)\n"
                     "11 < u ≤ 15: Zu = 1 / (1.246154 + 2.039188 / u)\n"
                     "15 < u ≤ 20: Zu = e^-0.4985559 · u^0.0646027\n"
                     "20 < u ≤ 73: Zu = e^-0.2770134 · e^(-0.5298417 / u)\n"
                     "u > 73:     Zu = 0.753"),
         "terms": [("Zu", "ratio correction factor", "-"),
                   ("u", "gear ratio", "-")]},
        {"ref": "Annex G.4", "title": "Face width and materials factor Zm (piecewise, x = a/25.4)",
         "formula": ("a ≤ 152:      Zm = e^-0.7882931 · x^0.4478914\n"
                     "152 < a ≤ 305: Zm = e^-0.5025085 · x^0.29122965\n"
                     "305 < a ≤ 555: Zm = 1 / (0.894949 - 0.00030721 · a)\n"
                     "a > 555:     Zm = e^0.0042213 · x^0.1046893"),
         "terms": [("Zm", "face width and materials factor", "-"),
                   ("a", "center distance", "mm"),
                   ("x", "center distance in inches (a/25.4)", "-")]},
        {"ref": "Table 6", "title": "Velocity factor Zv",
         "formula": "Zv = interpolated from table 6 at Vg (clamped to 0 - 30 m/s)",
         "terms": [("Zv", "velocity factor", "-"),
                   ("Vg", "sliding velocity", "m/s")]},
        {"ref": "Clause 8.1.3", "title": "Gear speed and torques at rating",
         "formula": ("n2 = n1 / u\n"
                     "T1 = 9549.297 · P1 / n1\n"
                     "T2 = T1 · u · η\n"
                     "P2 = P1 · η"),
         "terms": [("n2", "gear speed", "rpm"),
                   ("T1", "worm torque", "N·m"),
                   ("T2", "gear torque", "N·m"),
                   ("P2", "output power at rating", "kW"),
                   ("η", "reducer efficiency (input, or estimated from figure F.1)", "-"),
                   ("P1", "input power rating", "kW")]},
        {"ref": "Annex D, clause 8.6.2", "title": "Service factor and allowable power",
         "formula": "P1 / SF   (SF from table D.1 or user input)",
         "terms": [("SF", "service factor (hours per day and load type)", "-"),
                   ("P1", "input power rating", "kW")]},
    ]),
    ("Gearing forces (Annex B)", [
        {"ref": "Eq. (B.1)", "title": "Gear tangential force (= worm axial thrust)",
         "formula": "Wt2 = 2000 · T2 / dm2",
         "terms": [("Wt2", "gear tangential force", "N"),
                   ("T2", "gear torque", "N·m"),
                   ("dm2", "gear mean diameter", "mm")]},
        {"ref": "Eq. (B.2)", "title": "Separating force",
         "formula": "Ws = Wt2 · tan αx",
         "terms": [("Ws", "separating force", "N"),
                   ("Wt2", "gear tangential force", "N"),
                   ("αx", "axial pressure angle", "deg")]},
        {"ref": "Eq. (B.3)", "title": "Worm tangential force (= gear axial thrust)",
         "formula": "Wa2 = 2000 · T1 / dm1",
         "terms": [("Wa2", "worm tangential force", "N"),
                   ("T1", "worm torque", "N·m"),
                   ("dm1", "worm mean diameter", "mm")]},
        {"ref": "Clause B.2", "title": "Mean diameters",
         "formula": "dm1 = da1 - h1 ;  dm2 = 2a - dm1",
         "terms": [("dm1", "worm mean diameter", "mm"),
                   ("dm2", "gear mean diameter", "mm"),
                   ("da1", "worm throat diameter", "mm"),
                   ("h1", "whole depth", "mm"),
                   ("a", "center distance", "mm")]},
    ]),
    ("Worm shaft bearings, bending and deflection (Annex B)", [
        {"ref": "Eq. (B.4)", "title": "Reaction at bearing A",
         "formula": "RA = √( (Wt2·dm1/(2L) + Ws·lB/L)² + (Wa2·lB/L)² )",
         "terms": [("RA", "radial reaction at bearing A", "N"),
                   ("Wt2, Ws, Wa2", "gear tangential, separating and worm tangential forces", "N"),
                   ("dm1", "worm mean diameter", "mm"),
                   ("L", "bearing span = lA + lB", "mm"),
                   ("lA, lB", "pitch point to bearing A and B", "mm")]},
        {"ref": "Eq. (B.5)", "title": "Reaction at bearing B",
         "formula": "RB = √( (Wt2·dm1/(2L) - Ws·lA/L)² + (Wa2·lA/L)² )",
         "terms": [("RB", "radial reaction at bearing B", "N"),
                   ("Wt2, Ws, Wa2", "gear tangential, separating and worm tangential forces", "N"),
                   ("dm1", "worm mean diameter", "mm"),
                   ("L", "bearing span", "mm"),
                   ("lA, lB", "pitch point to bearing A and B", "mm")]},
        {"ref": "Eq. (B.6)", "title": "Worm shaft bending moment",
         "formula": "M = max(RA·lA, RB·lB) / 1000",
         "terms": [("M", "maximum bending moment", "N·m"),
                   ("RA, RB", "bearing reactions", "N"),
                   ("lA, lB", "pitch point to bearing A and B", "mm")]},
        {"ref": "Eq. (B.7)", "title": "Worm bending stress",
         "formula": "Sb = 32 000 · M / (π · df1³)",
         "terms": [("Sb", "bending stress in the worm core", "N/mm²"),
                   ("M", "bending moment", "N·m"),
                   ("df1", "worm root diameter", "mm")]},
        {"ref": "Eq. (B.8)", "title": "Equivalent force",
         "formula": "F = RA + RB",
         "terms": [("F", "equivalent force", "N"),
                   ("RA, RB", "bearing reactions", "N")]},
        {"ref": "Eq. (B.9)", "title": "Worm deflection in the central plane",
         "formula": "y = F·L³ / (3·E·I) · (1 - k) · (2k/3 - k²/3)^1.5",
         "terms": [("y", "worm deflection", "mm"),
                   ("F", "equivalent force", "N"),
                   ("L", "bearing span", "mm"),
                   ("E", "modulus of elasticity of the worm", "N/mm²"),
                   ("I", "second moment of area at the root diameter", "mm⁴"),
                   ("k", "load location factor = max(RA, RB) / F", "-")]},
        {"ref": "Eq. (B.10)", "title": "Second moment of area at root diameter",
         "formula": "I = π · df1⁴ / 64",
         "terms": [("I", "second moment of area", "mm⁴"),
                   ("df1", "worm root diameter", "mm")]},
        {"ref": "Clause B.4.1", "title": "Allowable worm bending stress",
         "formula": "Sb ≤ 0.17 · UTS   ;   3 · Sb · (P1/Pin) ≤ 0.75 · yield",
         "terms": [("UTS", "worm core ultimate tensile strength", "N/mm²"),
                   ("yield", "worm core yield strength", "N/mm²"),
                   ("P1/Pin", "rated to applied input power ratio", "-")]},
        {"ref": "Clause B.5.1", "title": "Allowable worm deflection",
         "formula": "y_allow = 0.025 · √pt2",
         "terms": [("y_allow", "allowable worm deflection", "mm"),
                   ("pt2", "transverse circular pitch", "mm")]},
    ]),
    ("Table and figure look-ups (no equation)", [
        {"ref": "Figure F.1", "title": "Efficiency estimate η",
         "formula": "Read from figure F.1 by gear ratio u and worm speed n1 (interpolated)",
         "terms": [("η", "reducer efficiency; overridden if entered by the user", "%")]},
        {"ref": "Table D.1", "title": "Service factor SF",
         "formula": "Read from table D.1 by hours per day and load type (next tabulated hours up)",
         "terms": [("SF", "service factor; overridden if entered by the user", "-")]},
        {"ref": "Table 2", "title": "Recommended number of gear teeth",
         "formula": "Looked up by center distance a",
         "terms": [("z2", "recommended range of teeth for the center distance", "-")]},
    ]),
]
